CONFIG_GPIO=y
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_DYNAMIC_INTERRUPTS=y
CONFIG_PRINTK=y
# CONFIG_CBPRINTF_FP_SUPPORT=y
# CONFIG_ADC=y

# Habilita a API genérica de Sensores do Zephyr.
# O sistema de build verá o `compatible` no overlay e habilitará
# automaticamente CONFIG_FXOS8700 e CONFIG_I2C como dependências.
CONFIG_SENSOR=y
# Habilita o suporte a números de ponto flutuante na função printk
CONFIG_NEWLIB_LIBC=y
CONFIG_CBPRINTF_FP_SUPPORT=y
# # Habilita o subsistema de log
# CONFIG_LOG=y               

# # Mostra mensagens até LOG_INF (níveis: 0–4) 
# CONFIG_LOG_DEFAULT_LEVEL=3  

# # (opcional) envia logs por uma fila, sem travar threads
# CONFIG_LOG_MODE_DEFERRED=y